name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x.x'
    - uses: actions/checkout@v2
    - name: Install dependencies dotnet
      run: dotnet restore
    - name: Build dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Test dotnet
      run: dotnet test --no-restore --verbosity normal
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: NPM install
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    - name: NPM build
      run: cd DotnetTemplate.Web && npm run build
